### **Connect With Me in Linkedin  :-** https://www.linkedin.com/in/dheerajkumar1997/

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

# Giving Knowledge as Corpus

In [8]:
Corpus = ["""DATA : It can be any unprocessed fact, value, text, sound or picture that is not being interpreted and analyzed.""", 
"""Data is the most important part of all Data Analytics, Machine Learning, Artificial Intelligence.""",
"""Without data, we can’t train any model and all modern research and automation will go vain.""",
"""Big Enterprises are spending loads of money on Data with Machine Learning and Artificial Intelligence""",
"""Data that has been interpreted and manipulated and has now some meaningful inference for the users.""",
"""Data is manipulated through software, calculations, graphs etc. as per own convenience"""]

In [9]:
voc_size=10000

# OneHot Representation

In [10]:
onehot_rep = [one_hot(words,voc_size)for words in Corpus]
print(onehot_rep)

[[7154, 3223, 1240, 2616, 1312, 8086, 3103, 658, 170, 4191, 4165, 5538, 9536, 9741, 3341, 3236, 3300, 9026, 2988], [7154, 9741, 2862, 8731, 354, 2306, 7467, 8033, 7154, 8015, 279, 9463, 1240, 4175], [5100, 7154, 7318, 315, 1658, 1312, 9168, 9026, 8033, 1748, 9866, 9026, 1728, 4869, 984, 9273], [4032, 5024, 6016, 8895, 3714, 7467, 3641, 6299, 7154, 9314, 279, 9463, 9026, 1240, 4175], [7154, 9536, 8479, 1657, 3300, 9026, 982, 9026, 8479, 7305, 5776, 1270, 8774, 4189, 2862, 2597], [7154, 9741, 982, 1557, 8087, 7772, 8725, 938, 2949, 6872, 222, 9130]]


# Word Embedding Representation

In [15]:
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
Corpus_length = 10
embedded_docs = pad_sequences(onehot_rep,padding='pre',maxlen=Corpus_length)
embedded_docs

array([[4191, 4165, 5538, 9536, 9741, 3341, 3236, 3300, 9026, 2988],
       [ 354, 2306, 7467, 8033, 7154, 8015,  279, 9463, 1240, 4175],
       [9168, 9026, 8033, 1748, 9866, 9026, 1728, 4869,  984, 9273],
       [7467, 3641, 6299, 7154, 9314,  279, 9463, 9026, 1240, 4175],
       [ 982, 9026, 8479, 7305, 5776, 1270, 8774, 4189, 2862, 2597],
       [ 982, 1557, 8087, 7772, 8725,  938, 2949, 6872,  222, 9130]])

In [ ]:
dim = 15

In [17]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=Corpus_length))
model.compile('adam','mse')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [19]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 10, 10)            100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.predict(embedded_docs)

array([[[ 1.29163601e-02,  2.94207446e-02, -1.00821629e-02,
          4.72815745e-02, -4.79095057e-03,  5.91062382e-03,
          4.70928662e-02, -1.90698504e-02,  4.20959480e-02,
          3.16706039e-02],
        [ 4.41333540e-02, -3.64115722e-02, -1.81815028e-02,
          2.47444175e-02, -4.29888628e-02,  1.41556971e-02,
          3.77068557e-02,  4.37469818e-02, -1.82995088e-02,
          6.72090799e-04],
        [-2.26654653e-02, -2.88991928e-02,  4.34739850e-02,
          3.46751846e-02,  3.59014161e-02, -3.32378522e-02,
          4.30773608e-02, -2.98320651e-02,  1.87741555e-02,
          8.30023363e-03],
        [ 2.03174986e-02, -1.59500912e-03,  1.79644488e-02,
         -4.02846821e-02,  3.84158604e-02, -8.80004093e-03,
         -1.08792633e-03, -9.45676118e-04,  8.55810940e-05,
          3.57151516e-02],
        [ 1.94409154e-02,  1.72067806e-03,  3.96562926e-02,
         -4.05477062e-02,  2.75353231e-02, -4.03735414e-02,
         -1.04619265e-02, -1.68600902e-02,  4.097023

In [21]:
embedded_docs[0]

array([4191, 4165, 5538, 9536, 9741, 3341, 3236, 3300, 9026, 2988])

In [23]:
model.predict(embedded_docs)[0]

array([[ 1.29163601e-02,  2.94207446e-02, -1.00821629e-02,
         4.72815745e-02, -4.79095057e-03,  5.91062382e-03,
         4.70928662e-02, -1.90698504e-02,  4.20959480e-02,
         3.16706039e-02],
       [ 4.41333540e-02, -3.64115722e-02, -1.81815028e-02,
         2.47444175e-02, -4.29888628e-02,  1.41556971e-02,
         3.77068557e-02,  4.37469818e-02, -1.82995088e-02,
         6.72090799e-04],
       [-2.26654653e-02, -2.88991928e-02,  4.34739850e-02,
         3.46751846e-02,  3.59014161e-02, -3.32378522e-02,
         4.30773608e-02, -2.98320651e-02,  1.87741555e-02,
         8.30023363e-03],
       [ 2.03174986e-02, -1.59500912e-03,  1.79644488e-02,
        -4.02846821e-02,  3.84158604e-02, -8.80004093e-03,
        -1.08792633e-03, -9.45676118e-04,  8.55810940e-05,
         3.57151516e-02],
       [ 1.94409154e-02,  1.72067806e-03,  3.96562926e-02,
        -4.05477062e-02,  2.75353231e-02, -4.03735414e-02,
        -1.04619265e-02, -1.68600902e-02,  4.09702323e-02,
         5.

### **Connect With Me in Linkedin  :-** https://www.linkedin.com/in/dheerajkumar1997/